[package]
name = "urbit-rust"
version = "0.1.0"
authors = ["clonex10100 <clonex10100@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ramp = "0.5.9"
